services:
  db:
    image: mariadb:5.5
    container_name: tdss-database
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1q2w3e4r
      - TZ=Asia/Bangkok
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - tsunami
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: tdss-pma
    restart: always
    environment:
      - UPLOAD_LIMIT=256M
    ports:
      - 8080:80
    networks:
      - tsunami
  app:
    image: tdss-webapp-img
    container_name: tdss-webapp
    restart: always
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./www:/var/www/html
      - ./workspace:/var/www/html/workspace
    networks:
      - tsunami

volumes:
  db-data:
    external: true
networks:
  tsunami: